### ISSUE TITLE
Question about fewshot.py

### ISSUE THREAD

**Issue by YulunGuo** [zy1296/CrackNex#1]
Thank you for your great work, it helps me a lot. But when i try to run code, i found a mistake.
`
 if self.mode == 'train':
            # base classes = all classes - novel classes
            self.classes = set(range(interval * self.fold + 1, interval * (self.fold + 1) + 1))
        else:
            # novel classes
            self.classes = set(range(1, n_class + 1)) - set(range(interval * self.fold + 1, interval * (self.fold + 1) + 1))
`
I do not really understand this part and it will make the image id list null.

**Comment by zyaocoder** [comment]
Thank you for your interest.

Basically, this part of code is built upon the SSP and this is used to split all base/novel classes. I was wondering if you ran the original code with the LCSD dataset. Did you change the default setting of fold or interval?

**Comment by YulunGuo** [comment]
Thank you for your response, i ran the original code with the LCSD dataset and i do not change the default setting.

When i debug with train mode ( `self.classes = {1}` ), i find the function `_filter_ids()` will delete all values of `self.ids`  and it will make the train process error. 

The problem occurs in the part below ( I guess the mask may be divided by 255 ？):
`mask = Image.fromarray(np.array(Image.open(os.path.join(self.mask_path, self.ids[i] + '.png')))) `
`classes = set(np.unique(mask)) & self.classes`

And when i debug with the val mode ( `self.classes = {2}` ), `classes = set(np.unique(mask)) & self.classes` will return `{}` and this will       also  make `_filter_ids()` delete all values of `self.ids` .

**Comment by zyaocoder** [comment]
Could you debug and see if the path is correct? If so, could you then figure out the value of `np.unique(mask)`?

**Comment by YulunGuo** [comment]
Sure and the value of `np.unique(mask)` is shown below.
<img width="773" alt="1726290644540" src="https://github.com/user-attachments/assets/652d6bc6-cd7f-45f3-8740-38efb41e7901">

**Comment by zyaocoder** [comment]
It seems like your installed PIL package automatically converted the mask value from 1 to 255 since the original value is [0, 1, 2]. You might try to install Pillow version 8.4 instead.

**Comment by YulunGuo** [comment]
Ok, i will try it. 

Thank you for your patience.
